name: build-system

inputs:
  otp-version:
    required: true
  elixir-version:
    required: true
  nerves-bootstrap-version:
    required: true
  hex-validate:
    required: false
    type: boolean
    default: true
  enable-ccache:
    required: false
    type: boolean
    default: true
  store-artifacts:
    required: false
    type: boolean
    default: true
  ccache-initial-setup:
    required: false
    default: --max-size=1G
  working-directory:
    required: false
    description: Working directory for the mix project
    default: "."

runs:
  using: composite
  steps:
    - uses: ./.actions/.internal/setup-beam-nerves
      with:
        otp-version: ${{ inputs.otp-version }}
        elixir-version: ${{ inputs.elixir-version }}
        nerves-bootstrap-version: ${{ inputs.nerves-bootstrap-version }}
        working-directory: ${{ inputs.working-directory }}
    - uses: ./.actions/.internal/restore-nerves-downloads
    - uses: ./.actions/.internal/mix-deps-get
      with:
        cd: ${{ inputs.working-directory }}
    - name: Validate Hex package
      if: inputs.hex-validate == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: mix hex.build
    - name: Restore ccache
      if: inputs.enable-ccache == 'true'
      uses: ./.actions/.internal/cache-buildroot-ccache
    - name: Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [[ "${{ inputs.enable-ccache }}" = "true" ]]; then
          export BR2_CCACHE=y
          export BR2_CCACHE_DIR=~/.buildroot-ccache
          export BR2_CCACHE_INITIAL_SETUP="${{ inputs.ccache-initial-setup }}"
        fi
        mix compile
    - name: Did I really build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        [ -d .nerves ] || (echo "VERSION file needs to be bumped or a config file needs to change to force a build"; exit 1)
    - name: Lint
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Ensure dev dependencies are available for linting
        MIX_ENV=dev mix deps.get
        MIX_ENV=dev mix nerves.system.lint nerves_defconfig
    - name: Create artifacts
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        mkdir -p deploy/system/artifacts
        cp ./CHANGELOG.md deploy/system/CHANGELOG.md
        mix nerves.artifact ${GITHUB_REPOSITORY#*/} --path deploy/system/artifacts
    - name: Store artifacts
      if: inputs.store-artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        path: ${{ inputs.working-directory }}/deploy/system/artifacts
        name: system
    - name: Save deploy cache
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.working-directory }}/deploy/system
        key: deploy/system-${{ github.sha }}-${{ github.ref_name }}
